name: echo-comments
on:
  issue_comment:
    types:
      - created
jobs:
  echo-content:
    runs-on: ubuntu-latest
    if: ${{ github.event.comment.body == 'Approved'}}
    steps:
    - name: echo-body
      env: 
        BODY: ${{ github.event.issue.body }}
      run: echo $BODY
    
