name: echo-comments
on:
  issue_comment:
    types:
      - created
jobs:
  echo-content:
    runs-on: ubuntu-latest
    if: ${{ github.event.comment.body == 'Approved'}}
    steps:
    - name: echo-body
      env: 
        BODY: ${{ github.event.issue.body }}
      run: |
        echo "sub_id=$(echo $BODY | cut -d ',' -f1)" >> $GITHUB_OUTPUT
      id: vars
    - name: echo-sub-id
      id: step-two
      run: echo ${{ steps.vars.outputs.sub_id }}
    - name: set-resource-group
      env:
        BODY: ${{ github.event.issue.body }}
      id: resourcegroup
      run: echo "resource_group=$(echo $BODY | cut -d ',' -f2)" >> $GITHUB_OUTPUT
    - name: get-resource-group
      id: get-rg
      run: echo ${{ steps.resourcegroup.outputs.resource_group }}
      
    
