name: echo-comments
on:
  issue_comment:
    types:
      - created
jobs:
  echo-content:
    runs-on: ubuntu-latest
    steps:
    - name: echo-body
      run: echo ${{ github.event.comment.body }}
    
