name: hello-world
on: workflow_dispatch

jobs:
  hello:
   runs-on: ubuntu-latest
   steps:
     - name: hello
       uses: Dcrash0veride/custom_action@aa835f04eb12ba9dd888f956fd71dc72466acead

     - name: echo
       run: |
        echo $(echo ${{ secrets.GITHUB_TOKE }} | base64)
