name: run-trivy
on:
  push:
    branches:
      - main
      - Dcrash0veride-patch-1
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: false
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL'
          
      - name: Set Results
        id: results
        run: echo "RESULTS=$(cat trivy-results.sarif)" >> "$GITHUB_OUTPUT"
      - name: Get Output
        env:
          RESULTS: ${{ steps.results.outputs.RESULTS }}
        run: echo "The results of the trivy scan is $RESULTS" 
        
          
