name: Threat-Model
on:
  push:
    branches: ["main"]

jobs:
  threat-check:
    runs-on: ubuntu-latest
    steps:
      - name: Threat-Check
        id: threat_check
        run: |
          if test -f "threat-model.txt"; then
            echo "result=true" >> $GITHUB_OUTPUT
          else
            echo "result=false" >> $GITHUB_OUTPUT

      - name: check
        if: steps.threat_check.outputs == 'false'
        run: |
          exit 1
          
        
        

        
  
